// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQG49GdDVvtRHbSD18QmXP2wnVS4t_X1M',
    appId: '1:608719551060:web:0827ba511cce45f0374bc1',
    messagingSenderId: '608719551060',
    projectId: 'authentication-bcd92',
    authDomain: 'authentication-bcd92.firebaseapp.com',
    storageBucket: 'authentication-bcd92.appspot.com',
    measurementId: 'G-9B9J7D4HXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv2CIfVD3fnN4QmZqfkko3U_jgZWF7gjE',
    appId: '1:608719551060:android:b75f4db8a41e7fc2374bc1',
    messagingSenderId: '608719551060',
    projectId: 'authentication-bcd92',
    storageBucket: 'authentication-bcd92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL4a6rq77eWEpmiWN5tMrQ1knM-DpAj5Y',
    appId: '1:608719551060:ios:acf82684cdb8da93374bc1',
    messagingSenderId: '608719551060',
    projectId: 'authentication-bcd92',
    storageBucket: 'authentication-bcd92.appspot.com',
    iosClientId: '608719551060-624ur8jpbg82bgc2ke22hl2j7q95veu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL4a6rq77eWEpmiWN5tMrQ1knM-DpAj5Y',
    appId: '1:608719551060:ios:acf82684cdb8da93374bc1',
    messagingSenderId: '608719551060',
    projectId: 'authentication-bcd92',
    storageBucket: 'authentication-bcd92.appspot.com',
    iosClientId: '608719551060-624ur8jpbg82bgc2ke22hl2j7q95veu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );
}
